---
# tasks file for roles/etcd
- name: 下载etcd二进制文件
  copy: src={{ base_dir }}/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - etcd
  - etcdctl
  tags: upgrade_etcd


- name: 创建etcd的systemd unit文件
  template: src=etcd.service.j2 dest=/etc/systemd/system/etcd.service
  tags: upgrade_etcd


- name: 创建etcd工作目录
  file: name=/var/lib/etcd state=directory


- name: 创建 etcd 配置目录
  file: name=/etc/etcd state=directory

- name: 创建 etcd.conf 文件
  template: src=etcd.conf.j2 dest=/etc/etcd/etcd.conf
  tags: upgrade_etcd


- name: 读取etcd证书stat信息
  stat: path="/etc/etcd/ssl/etcd.pem"
  register: p

- name: 创建 etcd 证书目录
  file: name=/etc/etcd/ssl state=directory

- name: 创建etcd证书请求
  template: src=etcd-csr.json.j2 dest=/etc/etcd/ssl/etcd-csr.json
  when: p.stat.isreg is not defined

- name: 创建 etcd证书和私钥
  when: p.stat.isreg is not defined
  shell: "cd /etc/etcd/ssl && {{ bin_dir }}/cfssl gencert \
        -ca={{ ca_dir }}/ca.pem \
        -ca-key={{ ca_dir }}/ca-key.pem \
        -config={{ ca_dir }}/ca-config.json \
        -profile=kubernetes etcd-csr.json | {{ bin_dir }}/cfssljson -bare etcd"

- name: 开机启用etcd服务
  shell: systemctl enable etcd
  ignore_errors: true

- name: 开启etcd服务
  shell: systemctl daemon-reload && systemctl restart etcd
  tags: upgrade_etcd
