---
# tasks file for roles/prepare

- name: 删除centos默认安装
  yum:
    name:
      - firewalld
      - python-firewall
      - firewalld-filesystem
      - dnsmasq
    state: absent


- name: 安装基础软件包
  yum:
    name:
      - epel-release
      - conntrack-tools
      - psmisc
      - nfs-utils
      - jq
      - socat
      - bash-completion
      - rsync
      - ipset
      - ipvsadm
      - libselinux-python
      - nmap-ncat
    state: latest

- name: 临时关闭 selinux
  shell: "setenforce 0"
  failed_when: false

- name: 永久关闭 selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: 设置 Centos ulimits
  template: src=k8s-limits.conf.j2 dest=/etc/security/limits.d/k8s-limits.conf

- name: 关闭 swap
  shell: "swapoff -a && sysctl -w vm.swappiness=0"
  ignore_errors: true

- name: fstab swap 相关配置
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent
    backup: 'yes'

- name: 加载内核模块
  modprobe: name={{ item }} state=present
  with_items:
    - br_netfilter
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack_ipv4
    - nf_conntrack
  ignore_errors: true

- name: 设置系统参数
  template: src=k8s-sysctl.conf.j2 dest=/etc/sysctl.d/k8s-sysctl.conf
- name: 生效系统参数
  shell: "sysctl -p /etc/sysctl.d/k8s-sysctl.conf"


- name: 写入环境变量$PATH
  lineinfile:
    dest: ~/.bashrc
    state: present
    regexp: 'kubeasz'
    line: 'export PATH={{ bin_dir }}:$PATH # generated by kubeasz'

- name: 添加 kubectl 命令自动补全
  lineinfile:
    dest: ~/.bashrc
    state: present
    regexp: 'kubectl completion'
    line: 'source <(kubectl completion bash)'


- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
  - "{{ bin_dir }}"
  - "{{ ca_dir }}"
  - "/root/.kube"

- name: 分发 kubectl
  copy: src={{ base_dir }}/bin/kubectl dest={{ bin_dir }}/kubectl mode=0755
  tags: upgrade_k8s

- name: 分发 kubectl kubeconfig配置文件
  synchronize: src=/root/.kube/config dest=/root/.kube/config

- name: 分发证书相关
  synchronize: src={{ ca_dir }}/{{ item }} dest={{ ca_dir }}/{{ item }}
  with_items:
  - admin.pem
  - admin-key.pem
  - ca.pem
  - ca-key.pem
  - ca.csr
  - ca-config.json

- name: 分发 cfssl
  copy: src={{ base_dir }}/bin/cfssl dest={{ bin_dir }}/cfssl mode=0755

- name: 分发 cfssl-certinfo
  copy: src={{ base_dir }}/bin/cfssl-certinfo dest={{ bin_dir }}/cfssl-certinfo mode=0755

- name: 分发 cfssljson
  copy: src={{ base_dir }}/bin/cfssljson dest={{ bin_dir }}/cfssljson mode=0755