---
# tasks file for roles/common/env-init
- name: ntp ntpdate ntp-doc install
  package:
    name:
      - ntp
      - ntpdate
      - ntp-doc

- name: ntpd enable and start
  systemd:
    name: ntpd
    state: started
    enabled: yes

- name: hostname config
  shell: hostnamectl set-hostname {{ inventory_hostname }}

- name: Disable SELinux
  selinux:
    state: disabled


# - name: Generate /etc/hosts file
#   template:
#     src: hosts.j2
#     dest: /etc/hosts


- name: requiretty config
  lineinfile:
    path: /etc/sudoers
    line: "#Defaults requiretty"
    regexp: '^Defaults requiretty'

- name: ssh config 1
  lineinfile:
    path: /etc/ssh/sshd_config
    state: absent
    line: PermitRootLogin yes
    regexp: '^PermitRootLogin'

- name: ssh config 2
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    line: PasswordAuthentication no
    regexp: '^PasswordAuthentication'

- name: sshd reload
  shell: systemctl reload sshd

- name: timezone config
  shell: timedatectl set-timezone Asia/Hong_Kong

- name: python-dnf install
  yum:
    name: python-dnf
    state: present

- name: useful tools install
  yum:
    name: [
    'bash-completion',
    'net-tools',
    'nc',
    'curl',
    'yum-utils',
    'vim',
    'epel-release',
    'rsync',
    'bind-utils',
    'wget',
    'ntpdate',
    'lrzsz',
    'sshpass',
    'lsof',
    'sysstat',
    'iotop'
    ]
    state: present

- name: pip script get
  get_url:
      url: https://bootstrap.pypa.io/get-pip.py
      dest: /tmp/get-pip.py

- name: pip install
  shell: python /tmp/get-pip.py

- name: supervisor install
  shell: pip install supervisor && echo_supervisord_conf > /etc/supervisord.conf

- name: create /etc/supervisor.d
  file:
    path: /etc/supervisor.d
    state: directory

- name: modify /etc/supervisord.conf
  blockinfile:
    path: /etc/supervisord.conf
    block: |
      [include]
      files = /etc/supervisor.d/*.conf

- name: supervisord.service config
  template:
    src: supervisord.service
    dest: /usr/lib/systemd/system/supervisord.service

- name: supervisord conf file
  file:
    path: /usr/lib/systemd/system/supervisord.service
    mode: 0766


- name: supervisord start
  systemd:
    name: supervisord
    state: restarted
    enabled: yes

- name: sysctl config
  blockinfile:
    path: /etc/sysctl.d/k8s.conf
    create: yes
    block: "net.bridge.bridge-nf-call-iptables = 1\nnet.bridge.bridge-nf-call-ip6tables = 1\nnet.bridge.bridge-nf-call-arptables = 1\nvm.swappiness = 0\nnet.ipv4.ip_forward = 1\nnet.netfilter.nf_conntrack_max=1000000\nvm.max_map_count=655360\nvm.overcommit_memory=1\nvm.panic_on_oom=0\nfs.inotify.max_user_watches=89100"
    state: present

- name: sysctl --system
  shell: sysctl --system

- name: add devops pub key1
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/Volumes/123/ansible-playbooks/roles/common/env-init/files/prod-devops_id.pub') }}"

- name: add devops pub key2
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/Volumes/123/ansible-playbooks/roles/common/env-init/files/devops_id.pub') }}"

- name: add cephadmin pub key
  authorized_key:
    user: cephuser
    state: present
    key: "{{ lookup('file', '/Users/admin/tech/credentials/id_rsa.pub') }}"
