---
# tasks file for roles/system-tuning

- name: set fs.file-max
  sysctl:
    name: fs.file-max
    value: 2097152

- name: set fs.nr_open
  sysctl:
    name: fs.nr_open
    value: 2097152

- name: DefaultLimitNOFILE=2097152
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: DefaultLimitNOFILE
    line: DefaultLimitNOFILE=2097152

- name: soft   nofile
  lineinfile:
    path: /etc/security/limits.conf
    regexp: soft   nofile
    line: '*      soft   nofile      2097152'

- name: hard   nofile
  lineinfile:
    path: /etc/security/limits.conf
    regexp: hard   nofile
    line: '*      hard   nofile      2097152'

- name: set net.core.somaxconn
  sysctl:
    name: net.core.somaxconn
    value: 32768

- name: set net.ipv4.tcp_max_syn_backlog
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: 16384

- name: set net.core.netdev_max_backlog
  sysctl:
    name: net.core.netdev_max_backlog
    value: 16384

- name: set net.ipv4.ip_local_port_range
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: '1000 65535'

- name: set net.core.rmem_default
  sysctl:
    name: net.core.rmem_default
    value: 262144

- name: set net.core.wmem_default
  sysctl:
    name: net.core.wmem_default
    value: 262144

- name: set net.core.rmem_max
  sysctl:
    name: net.core.rmem_max
    value: 16777216

- name: set net.core.wmem_max
  sysctl:
    name: net.core.wmem_max
    value: 16777216

- name: set net.core.optmem_max
  sysctl:
    name: net.core.optmem_max
    value: 16777216

- name: set net.ipv4.tcp_rmem
  sysctl:
    name: net.ipv4.tcp_rmem
    value: '1024 4096 16777216'

- name: set net.ipv4.tcp_wmem
  sysctl:
    name: net.ipv4.tcp_wmem
    value: '1024 4096 16777216'

- name: set net.nf_conntrack_max
  sysctl:
    name: net.nf_conntrack_max
    value: 1000000

- name: set net.netfilter.nf_conntrack_max
  sysctl:
    name: net.netfilter.nf_conntrack_max
    value: 1000000

- name: add ip_conntrack module
  modprobe:
    name: ip_conntrack

- name: set net.netfilter.nf_conntrack_tcp_timeout_time_wait
  sysctl:
    name: net.netfilter.nf_conntrack_tcp_timeout_time_wait
    value: 30

- name: set net.ipv4.tcp_max_tw_buckets
  sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: 1048576

- name: set net.ipv4.tcp_fin_timeout
  sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: 15

- name: Erlang vm node.process_limit
  lineinfile:
    path: /opt/emqx/etc/emqx.conf
    regexp: node.process_limit
    line: node.process_limit = 2097152

- name: Erlang vm node.max_ports
  lineinfile:
    path: /opt/emqx/etc/emqx.conf
    regexp: node.max_ports
    line: node.max_ports = 1048576

- name: /opt/emqx/etc/emqx.conf listener.tcp.external = 0.0.0.0:1883
  lineinfile:
    path: /opt/emqx/etc/emqx.conf
    regexp: listener.tcp.external
    line: listener.tcp.external = 0.0.0.0:1883

- name: /opt/emqx/etc/emqx.conf listener.tcp.external.acceptors = 64
  lineinfile:
    path: /opt/emqx/etc/emqx.conf
    regexp: listener.tcp.external.acceptors
    line: listener.tcp.external.acceptors = 64

- name: /opt/emqx/etc/emqx.conf listener.tcp.external.max_connections = 1000000
  lineinfile:
    path: /opt/emqx/etc/emqx.conf
    regexp: listener.tcp.external.max_connections
    line: listener.tcp.external.max_connections = 1000000
